jupyter labextension install @jupyterlab/latex
jupyter labextension install @jupyterlab/plotly-extension
jupyter labextension install jupyterlab_bokeh
jupyter labextension install jupyterlab-drawio
jupyter labextension install @jupyterlab/git
jupyter labextension install @jupyterlab/github
jupyter labextension install jupyterlab_voyager
jupyter labextension install pylantern
jupyter labextension install jupyterlab_templates
